### ISSUE TITLE
Can't run tests with OpenJDK 11

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-camel-bridge#28]
e.g

```
testWithBlocking(io.vertx.camel.OutboundEndpointTest)  Time elapsed: 0.315 sec  <<< ERROR!
java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlRootElement
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.apache.camel.model.OptionalIdentifiedDefinition.getShortName(OptionalIdentifiedDefinition.java:79)
	at org.apache.camel.impl.DefaultNodeIdFactory.createId(DefaultNodeIdFactory.java:36)
	at org.apache.camel.model.RouteDefinitionHelper.forceAssignIds(RouteDefinitionHelper.java:151)
	at org.apache.camel.impl.DefaultCamelContext.startRoute(DefaultCamelContext.java:1073)
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:3540)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3271)
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:202)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3089)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3085)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3108)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3085)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:3022)
	at io.vertx.camel.OutboundEndpointTest.testWithBlocking(OutboundEndpointTest.java:360)
```

**Comment by vietj** [comment]
can you have a look @davsclaus ?

**Comment by davsclaus** [comment]
Ah you need to add some extra JARs with JAXB as they are no longer incl in the JDK itself.

At Camel we have a jdk9+ profile to add some dependencies and set compiler plugin args, a bit like here
https://github.com/apache/camel/blob/master/parent/pom.xml#L5741

**Comment by davsclaus** [comment]
I dont have JDK 11 installed, so anyone is welcome to give it a go if they beat me to it

**Comment by vietj** [comment]
@davsclaus I fixed it, using a jaxb dependency, the actual link you gave makes surefire fail (I don't know why). This is advocated as last resort in this blog post https://github.com/vert-x3/vertx-camel-bridge/issues/28
