### ISSUE TITLE
OutboundEndpointTest failure

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-camel-bridge#29]
```
testWithBlockingWithWorker(io.vertx.camel.OutboundEndpointTest)  Time elapsed: 10.4 sec  <<< ERROR!
com.jayway.awaitility.core.ConditionTimeoutException: com.jayway.awaitility.core.ConditionFactory.untilAtomic Callable expected <true> but was <false> within 10 seconds.
	at com.jayway.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:122)
	at com.jayway.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:87)
	at com.jayway.awaitility.core.ConditionFactory.until(ConditionFactory.java:764)
	at com.jayway.awaitility.core.ConditionFactory.untilAtomic(ConditionFactory.java:664)
	at io.vertx.camel.OutboundEndpointTest.testWithBlockingWithWorker(OutboundEndpointTest.java:401)
```

**Comment by davsclaus** [comment]
Cannot reproduce this currently
