### ISSUE TITLE
Update camel to 2.24.2

### ISSUE THREAD

**Issue by slinkydeveloper** [vert-x3/vertx-camel-bridge#32]
I'm trying to dump camel version to 2.24.2 but i get this error:

```
Running io.vertx.camel.InboundEndpointTest
Tests run: 13, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 248.021 sec <<< FAILURE! - in io.vertx.camel.InboundEndpointTest
testWithStompAndJson(io.vertx.camel.InboundEndpointTest)  Time elapsed: 120.151 sec  <<< ERROR!
java.util.concurrent.TimeoutException: null
	at io.vertx.ext.unit.impl.TestContextImpl.lambda$run$1(TestContextImpl.java:79)
	at java.base/java.lang.Thread.run(Thread.java:830)

testWithStomp(io.vertx.camel.InboundEndpointTest)  Time elapsed: 120.125 sec  <<< ERROR!
java.util.concurrent.TimeoutException: null
	at io.vertx.ext.unit.impl.TestContextImpl.lambda$run$1(TestContextImpl.java:79)
	at java.base/java.lang.Thread.run(Thread.java:830)

Running io.vertx.camel.impl.MultiMapHelperTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in io.vertx.camel.impl.MultiMapHelperTest
Running io.vertx.camel.impl.CamelHelperTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE! - in io.vertx.camel.impl.CamelHelperTest
testTheCopyOfHeaders(io.vertx.camel.impl.CamelHelperTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.IllegalArgumentException: CamelContext must be specified on: Message[]
	at org.apache.camel.util.ObjectHelper.notNull(ObjectHelper.java:340)
	at org.apache.camel.impl.DefaultMessage.createHeaders(DefaultMessage.java:255)
	at org.apache.camel.impl.DefaultMessage.setHeader(DefaultMessage.java:172)
	at io.vertx.camel.impl.CamelHelperTest.testTheCopyOfHeaders(CamelHelperTest.java:20)

Running io.vertx.camel.InboundReplyTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.269 sec - in io.vertx.camel.InboundReplyTest

Results :

Tests in error: 
  InboundEndpointTest.testWithStomp » Timeout
  InboundEndpointTest.testWithStompAndJson » Timeout
  CamelHelperTest.testTheCopyOfHeaders:20 » IllegalArgument CamelContext must be...

```

@davsclaus can you give a look at this? Thank you!

**Comment by vietj** [comment]
@davsclaus we are trying upgrading the Camel version in master, can you help us investigate ?

**Comment by davsclaus** [comment]
That is because CamelHelperTest is creating a new DefaultMessage without a CamelContext, you need to create a new DefaultCamelContext and set on that DefaultMessage.

**Comment by slinkydeveloper** [comment]
@davsclaus This fixes the problem on `CamelHelperTest`, but `InboundEndpointTest`s still don't pass. Any thoughts on these?

**Comment by vietj** [comment]
thanks Claus

**Comment by davsclaus** [comment]
Oh I forgot that unit testing vertx from within IDEA dont work, unless you do something I forgot :)

**Comment by davsclaus** [comment]
Found the solution
https://github.com/vert-x3/vertx-ext-parent/issues/7

**Comment by davsclaus** [comment]
PR with a fix for this
https://github.com/vert-x3/vertx-camel-bridge/pull/33

**Comment by slinkydeveloper** [comment]
Thank you so much!
