### ISSUE TITLE
NullPointerException on headers copy

### ISSUE THREAD

**Issue by phsmip** [vert-x3/vertx-camel-bridge#5]
I have connected a JMS Camel endpoint to a vertx consumer. During the process of the exchange, the hearders are copied into a DeliveryOptions object.

Some of the JMS headers were null, this is not handled by `CamelHelper.getDeliveryOptions()`.
Below, you can find the headers:
`{breadcrumbId=ID:meta-lhr-60035-1456501946892-3:30:1:1:7, CamelRedelivered=false,
CamelRedeliveryCounter=0, JMSCorrelationID=,
JMSCorrelationIDAsBytes=, JMSDeliveryMode=1,
JMSDestination=queue://dev.msy.queue.log.fwd,
JMSExpiration=0,JMSMessageID=ID:meta-lhr-60035-1456501946892-3:30:1:1:7,
JMSPriority=0, JMSRedelivered=false, JMSReplyTo=null, JMSTimestamp=1461662849614, JMSType=, JMSXGroupID=null, JMSXUserID=null, queue=1}`

I think the headers must be copied even if they are empty or null.

**Comment by cescoffier** [comment]
Do you have the stack trace ?

**Comment by phsmip** [comment]
Here is the stack:

<code>
2016-04-26 11:58:35.740 [DEBUG] [Camel (camel-1) thread #0 - JmsConsumer[dev.msy.queue.log.fwd]] DefaultErrorHandler - Failed delivery for (MessageId: ID:meta-lhr-60035-1456501946892-3:30:1:1:10 on ExchangeId: ID-SIGMA-61510-1461664705041-0-1). On delivery attempt: 0 caught: java.lang.NullPointerException
2016-04-26 11:58:35.745 [ERROR] [Camel (camel-1) thread #0 - JmsConsumer[dev.msy.queue.log.fwd]] DefaultErrorHandler - Failed delivery for (MessageId: ID:meta-lhr-60035-1456501946892-3:30:1:1:10 on ExchangeId: ID-SIGMA-61510-1461664705041-0-1). Exhausted after delivery attempt: 1 caught: java.lang.NullPointerException

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[logFwd            ] [logFwd            ] [metaJms://queue:dev.msy.queue.log.fwd                                         ] [        26]
[logFwd            ] [setHeader1        ] [setHeader[queue]                                                              ] [         3]
[logFwd            ] [to1               ] [direct:meta                                                                   ] [        17]

Exchange
---------------------------------------------------------------------------------------------------------------------------------------
Exchange[
	Id                  ID-SIGMA-61510-1461664705041-0-1
	ExchangePattern     InOnly
	Headers             {breadcrumbId=ID:meta-lhr-60035-1456501946892-3:30:1:1:10, CamelRedelivered=false, CamelRedeliveryCounter=0, JMSCorrelationID=, JMSCorrelationIDAsBytes=, JMSDeliveryMode=1, JMSDestination=queue://dev.msy.queue.log.fwd, JMSExpiration=0, JMSMessageID=ID:meta-lhr-60035-1456501946892-3:30:1:1:10, JMSPriority=0, JMSRedelivered=false, JMSReplyTo=null, JMSTimestamp=1461664715503, JMSType=, JMSXGroupID=null, JMSXUserID=null, queue=1}
	BodyType            String
	Body                {"imei": ....}

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
java.lang.NullPointerException
	at io.vertx.ext.camel.impl.CamelHelper.lambda$getDeliveryOptions$0(CamelHelper.java:46) ~[vertx-camel-bridge-3.3.0-SNAPSHOT.jar:?]
	at java.util.TreeMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_77]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_77]
	at io.vertx.ext.camel.impl.CamelHelper.getDeliveryOptions(CamelHelper.java:45) ~[vertx-camel-bridge-3.3.0-SNAPSHOT.jar:?]
	at io.vertx.ext.camel.impl.CamelToVertxProcessor.process(CamelToVertxProcessor.java:57) ~[vertx-camel-bridge-3.3.0-SNAPSHOT.jar:?]
	at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:62) ~[camel-core-2.16.1.jar:2.16.1]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:141) ~[camel-core-2.16.1.jar:2.16.1]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77) ~[camel-core-2.16.1.jar:2.16.1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:460) [camel-core-2.16.1.jar:2.16.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190) [camel-core-2.16.1.jar:2.16.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121) [camel-core-2.16.1.jar:2.16.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83) [camel-core-2.16.1.jar:2.16.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190) [camel-core-2.16.1.jar:2.16.1]
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.16.1.jar:2.16.1]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87) [camel-core-2.16.1.jar:2.16.1]
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:112) [camel-jms-2.16.1.jar:2.16.1]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:721) [spring-jms-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:681) [spring-jms-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651) [spring-jms-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315) [spring-jms-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253) [spring-jms-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150) [spring-jms-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142) [spring-jms-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039) [spring-jms-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_77]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
</code>

**Comment by cescoffier** [comment]
Can you build the project with https://github.com/vert-x3/vertx-camel-bridge/commit/4f36e5afa663a5dbf2ae8e8975d9c7924d60f278.

It should fix the issue.

**Comment by phsmip** [comment]
Thank you for the fix. I will try to build it.

Just one comment: headers with null values are not copied.
With this pattern, some headers will miss. For me, it could be interresting to have these headers transfered to vertx. These is a difference between no header, empty or null.

What is your advise?

**Comment by phsmip** [comment]
I have build the project and test it.
It's working.

Thank you.

**Comment by cescoffier** [comment]
I agree that non copying headers with a "null" value can be problematic. Vert.x header values cannot be null. Using a "specific" value could be a way to handle them, but on the other side it can become problematic too.

**Comment by cescoffier** [comment]
BTW, thanks for reporting the issue and gave the additional details. Made the fix quite easy !

**Comment by phsmip** [comment]
No problem, you are welcome.
